services:
  mysql:
    image: mysql:latest
    hostname: mysql
    restart: always
    environment:
      MYSQL_DATABASE: youstatsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - '3339:3306'
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'